# Auto-generated by `dotta __complete spec fish`.
# Dynamic completion helpers live in dotta.fish.

complete -c dotta -f

set -g __dotta_value_flags -p --profile --profiles --prefix -m --message -e --exclude --diverged --add --remove --test

# Root options
complete -c dotta -s h -l help -d "Show help"
complete -c dotta -s v -l version -d "Show version"
complete -c dotta -s i -l interactive -d "Interactive profile management and ordering"

# Commands
complete -c dotta -n __dotta_needs_command -a init -d "Initialize a new dotta repository"
complete -c dotta -n __dotta_needs_command -a clone -d "Clone an existing dotta repository"
complete -c dotta -n __dotta_needs_command -a add -d "Add files or directories to a profile"
complete -c dotta -n __dotta_needs_command -a remove -d "Remove files from a profile or delete profile"
complete -c dotta -n __dotta_needs_command -a update -d "Commit filesystem changes back to profiles"
complete -c dotta -n __dotta_needs_command -a apply -d "Deploy enabled profiles to the filesystem"
complete -c dotta -n __dotta_needs_command -a revert -d "Revert a file to a previous version"
complete -c dotta -n __dotta_needs_command -a status -d "Show workspace status and remote sync state"
complete -c dotta -n __dotta_needs_command -a diff -d "Show differences between profiles and filesystem"
complete -c dotta -n __dotta_needs_command -a list -d "List profiles, files, and commit history"
complete -c dotta -n __dotta_needs_command -a show -d "Show file content or commit details"
complete -c dotta -n __dotta_needs_command -a sync -d "Synchronize profiles with remote repository"
complete -c dotta -n __dotta_needs_command -a profile -d "Profile management and layering"
complete -c dotta -n __dotta_needs_command -a remote -d "Manage remote repositories"
complete -c dotta -n __dotta_needs_command -a ignore -d "Manage ignore patterns"
complete -c dotta -n __dotta_needs_command -a bootstrap -d "Execute profile bootstrap scripts"
complete -c dotta -n __dotta_needs_command -a key -d "Manage encryption keys and passphrases"
complete -c dotta -n __dotta_needs_command -a git -d "Execute git commands within repository"
complete -c dotta -n __dotta_needs_command -a interactive -d "Interactive profile management and ordering"

# init
complete -c dotta -n "__dotta_using_command init" -s q -l quiet -d "Suppress output"

# clone
complete -c dotta -n "__dotta_using_command clone" -s p -l profile -l profiles -r -d "Fetch specific profile(s) (repeatable)"
complete -c dotta -n "__dotta_using_command clone" -l all -d "Fetch every remote profile (hub/backup workflow)"
complete -c dotta -n "__dotta_using_command clone" -l bootstrap -d "Run bootstrap scripts without prompting"
complete -c dotta -n "__dotta_using_command clone" -l no-bootstrap -d "Skip bootstrap scripts entirely"
complete -c dotta -n "__dotta_using_command clone" -s q -l quiet -d "Suppress output"
complete -c dotta -n "__dotta_using_command clone" -s v -l verbose -d "Verbose output"

# add
complete -c dotta -n "__dotta_using_command add" -s p -l profile -r -d "Profile name (alternative to positional)"
complete -c dotta -n "__dotta_using_command add" -l prefix -r -d "Storage root for custom/ paths (e.g. /mnt/jails/web)"
complete -c dotta -n "__dotta_using_command add" -s m -l message -r -d "Commit message"
complete -c dotta -n "__dotta_using_command add" -s e -l exclude -r -d "Skip matching files (glob, repeatable)"
complete -c dotta -n "__dotta_using_command add" -s f -l force -d "Overwrite existing entries in the profile"
complete -c dotta -n "__dotta_using_command add" -s v -l verbose -d "Verbose output"
complete -c dotta -n "__dotta_using_command add" -l encrypt -d "Force encryption for the given files"
complete -c dotta -n "__dotta_using_command add" -l no-encrypt -d "Bypass auto-encrypt patterns"

# remove
complete -c dotta -n "__dotta_using_command remove" -s p -l profile -r -d "Profile name (alternative to positional)"
complete -c dotta -n "__dotta_using_command remove" -s m -l message -r -d "Commit message"
complete -c dotta -n "__dotta_using_command remove" -l delete-profile -d "Delete the entire profile branch"
complete -c dotta -n "__dotta_using_command remove" -l delete-files -d "Stage deployed copies for removal on next apply"
complete -c dotta -n "__dotta_using_command remove" -s n -l dry-run -d "Preview without writing"
complete -c dotta -n "__dotta_using_command remove" -s f -l force -d "Skip confirmation prompts"
complete -c dotta -n "__dotta_using_command remove" -s i -l interactive -d "Prompt for each file"
complete -c dotta -n "__dotta_using_command remove" -s v -l verbose -d "Verbose output"
complete -c dotta -n "__dotta_using_command remove" -s q -l quiet -d "Minimal output"

# update
complete -c dotta -n "__dotta_using_command update" -s m -l message -r -d "Commit message"
complete -c dotta -n "__dotta_using_command update" -s p -l profile -r -d "Filter update to profile(s) (repeatable)"
complete -c dotta -n "__dotta_using_command update" -s e -l exclude -r -d "Skip matching files (glob, repeatable)"
complete -c dotta -n "__dotta_using_command update" -s n -l dry-run -d "Preview without writing"
complete -c dotta -n "__dotta_using_command update" -s i -l interactive -d "Prompt per file before committing"
complete -c dotta -n "__dotta_using_command update" -s v -l verbose -d "Verbose output"
complete -c dotta -n "__dotta_using_command update" -l include-new -d "Also stage new files inside tracked directories"
complete -c dotta -n "__dotta_using_command update" -l only-new -d "Stage only new files; skip modifications"

# apply
complete -c dotta -n "__dotta_using_command apply" -s p -l profile -r -d "Filter deployment to profile(s) (repeatable)"
complete -c dotta -n "__dotta_using_command apply" -s e -l exclude -r -d "Skip matching files (no deploy, no removal)"
complete -c dotta -n "__dotta_using_command apply" -s f -l force -d "Overwrite modified files"
complete -c dotta -n "__dotta_using_command apply" -s n -l dry-run -d "Preview without writing"
complete -c dotta -n "__dotta_using_command apply" -l keep-orphans -d "Leave orphaned files in place (advanced)"
complete -c dotta -n "__dotta_using_command apply" -l skip-existing -d "Skip files that already exist"
complete -c dotta -n "__dotta_using_command apply" -l no-skip-unchanged -d "Redeploy every file, even if unchanged"
complete -c dotta -n "__dotta_using_command apply" -s v -l verbose -d "Verbose output"

# revert
complete -c dotta -n "__dotta_using_command revert" -s p -l profile -r -d "Disambiguate profile when file is ambiguous"
complete -c dotta -n "__dotta_using_command revert" -s m -l message -r -d "Commit message"
complete -c dotta -n "__dotta_using_command revert" -s f -l force -d "Skip confirmation and override conflicts"
complete -c dotta -n "__dotta_using_command revert" -s n -l dry-run -d "Preview without writing"
complete -c dotta -n "__dotta_using_command revert" -s v -l verbose -d "Verbose output"

# status
complete -c dotta -n "__dotta_using_command status" -s p -l profile -r -d "Filter status to profile(s) (repeatable)"
complete -c dotta -n "__dotta_using_command status" -l local -d "Restrict to filesystem status"
complete -c dotta -n "__dotta_using_command status" -l remote -d "Restrict to remote sync status"
complete -c dotta -n "__dotta_using_command status" -l no-fetch -d "Skip remote fetch; use cached refs"
complete -c dotta -n "__dotta_using_command status" -l all -d "Include non-enabled profiles"
complete -c dotta -n "__dotta_using_command status" -l no-sudo -d "Skip sudo; disables ownership checks"
complete -c dotta -n "__dotta_using_command status" -s v -l verbose -d "Verbose output"

# diff
complete -c dotta -n "__dotta_using_command diff" -s p -l profile -r -d "Filter diff to profile(s) (repeatable)"
complete -c dotta -n "__dotta_using_command diff" -l upstream -d "Preview apply: -/+ is filesystem/repo (default)"
complete -c dotta -n "__dotta_using_command diff" -l downstream -d "Preview update: -/+ is repo/filesystem"
complete -c dotta -n "__dotta_using_command diff" -s a -l all -d "Show both directions in labelled sections"
complete -c dotta -n "__dotta_using_command diff" -l name-only -d "Print changed file names only"

# list
complete -c dotta -n "__dotta_using_command list" -s p -l profile -r -d "Profile name (alternative to positional)"
complete -c dotta -n "__dotta_using_command list" -l remote -d "Show remote tracking state (Level 1 only)"
complete -c dotta -n "__dotta_using_command list" -s v -l verbose -d "Show detailed output"

# show
complete -c dotta -n "__dotta_using_command show" -s p -l profile -r -d "Override profile for file or commit lookup"
complete -c dotta -n "__dotta_using_command show" -l raw -d "Print raw file content without formatting"

# sync
complete -c dotta -n "__dotta_using_command sync" -s p -l profile -r -d "Filter sync to profile(s) (repeatable)"
complete -c dotta -n "__dotta_using_command sync" -s n -l dry-run -d "Preview without writing"
complete -c dotta -n "__dotta_using_command sync" -l no-push -d "Fetch and analyze only; skip push"
complete -c dotta -n "__dotta_using_command sync" -l no-pull -d "Push only; skip pull"
complete -c dotta -n "__dotta_using_command sync" -s f -l force -d "Sync even with uncommitted local changes"
complete -c dotta -n "__dotta_using_command sync" -l diverged -r -d "Diverged-branch strategy (see notes)"
complete -c dotta -n "__dotta_using_command sync" -s v -l verbose -d "Verbose output"

# profile
complete -c dotta -n "__dotta_using_command profile; and __dotta_needs_subcommand profile" -a list -d "Show all profiles and their enabled status"
complete -c dotta -n "__dotta_using_command profile; and __dotta_needs_subcommand profile" -a fetch -d "Download profiles from a remote without enabling them"
complete -c dotta -n "__dotta_using_command profile; and __dotta_needs_subcommand profile" -a enable -d "Enable profiles for deployment"
complete -c dotta -n "__dotta_using_command profile; and __dotta_needs_subcommand profile" -a disable -d "Disable profiles, mark for removal on next apply"
complete -c dotta -n "__dotta_using_command profile; and __dotta_needs_subcommand profile" -a reorder -d "Change the layering order of enabled profiles"
complete -c dotta -n "__dotta_using_command profile; and __dotta_needs_subcommand profile" -a validate -d "Check for and fix inconsistencies in the profile state"
complete -c dotta -n "__dotta_using_command profile; and __dotta_needs_subcommand profile" -l all -d "Show all available and remote profiles"
complete -c dotta -n "__dotta_using_subcommand profile list" -l all -d "Show all available and remote profiles"
complete -c dotta -n "__dotta_using_subcommand profile fetch" -l all -d "Fetch all remote profiles"
complete -c dotta -n "__dotta_using_subcommand profile fetch" -s v -l verbose -d "Show detailed progress"
complete -c dotta -n "__dotta_using_subcommand profile enable" -l all -d "Enable all local profiles"
complete -c dotta -n "__dotta_using_subcommand profile enable" -l prefix -r -d "Custom prefix for profiles with custom/ files"
complete -c dotta -n "__dotta_using_subcommand profile enable" -s v -l verbose -d "Show detailed progress"
complete -c dotta -n "__dotta_using_subcommand profile enable" -s q -l quiet -d "Suppress non-error output"
complete -c dotta -n "__dotta_using_subcommand profile disable" -l all -d "Disable all currently enabled profiles"
complete -c dotta -n "__dotta_using_subcommand profile disable" -s n -l dry-run -d "Show what would change without modifying state"
complete -c dotta -n "__dotta_using_subcommand profile disable" -s v -l verbose -d "Show detailed progress"
complete -c dotta -n "__dotta_using_subcommand profile disable" -s q -l quiet -d "Suppress non-error output"
complete -c dotta -n "__dotta_using_subcommand profile reorder" -s v -l verbose -d "Show the profile order before and after the change"
complete -c dotta -n "__dotta_using_subcommand profile reorder" -s q -l quiet -d "Suppress non-error output"
complete -c dotta -n "__dotta_using_subcommand profile validate" -l fix -d "Automatically fix any detected inconsistencies"

# remote
complete -c dotta -n "__dotta_using_command remote" -s v -l verbose -d "Show URLs (for list)"

# ignore
complete -c dotta -n "__dotta_using_command ignore" -s p -l profile -r -d "Profile name (alternative to positional)"
complete -c dotta -n "__dotta_using_command ignore" -l add -r -d "Append pattern to .dottaignore (repeatable)"
complete -c dotta -n "__dotta_using_command ignore" -l remove -r -d "Delete pattern from .dottaignore (repeatable)"
complete -c dotta -n "__dotta_using_command ignore" -l test -r -d "Report whether path is ignored"
complete -c dotta -n "__dotta_using_command ignore" -s v -l verbose -d "Verbose output (test mode: show matches)"

# bootstrap
complete -c dotta -n "__dotta_using_command bootstrap" -s p -l profile -r -d "Filter to profile(s) (repeatable)"
complete -c dotta -n "__dotta_using_command bootstrap" -l all -d "Run every available bootstrap script"
complete -c dotta -n "__dotta_using_command bootstrap" -s e -l edit -d "Edit the script (requires --profile)"
complete -c dotta -n "__dotta_using_command bootstrap" -l show -d "Print the script (requires --profile)"
complete -c dotta -n "__dotta_using_command bootstrap" -s l -l list -d "List all bootstrap scripts"
complete -c dotta -n "__dotta_using_command bootstrap" -s n -l dry-run -d "Preview execution without running"
complete -c dotta -n "__dotta_using_command bootstrap" -s y -l yes -l no-confirm -d "Skip confirmation prompts"
complete -c dotta -n "__dotta_using_command bootstrap" -l continue-on-error -d "Continue after a script failure"

# key
complete -c dotta -n "__dotta_using_command key" -s v -l verbose -d "Verbose output (status: show auto-encrypt patterns)"

# git
complete -c dotta -n "__dotta_using_command git" -xa "(__fish_complete_subcommand --command git)"

